config/routes.rb
Rails.application.routes.draw do
  get 'todos', to: 'todos#index'
  get 'todos/new'
  post 'todos', to: 'todos#create'
  get '/todos/list'
  get 'todos/:id', to: 'todos#show', as: 'todo'
  get 'todos/:id/edit', to: 'todos#edit', as:'edit_todo'
  patch 'todos/:id', to: 'todos#update'
  delete 'todos/:id', to: 'todos#destroy'
  post '/todos/:id/complete', to: 'todos#complete', as:'complete_todo'
  root 'todos#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
    before_action :find_todo, only: [:show, :edit, :update, :destroy, :complete]
    
    def index
        @todos = Todo.all
    end

    def new
        @todo = Todo.new
    end

    def create

        @todo=Todo.new(todo_params)
        @todo.save
        redirect_to todos_path

    end

    def show
    
    end

    def edit
    
    end

    def update
        @todo.update(todo_params)
        redirect_to todos_path
    end

    def destroy
        @todo.destroy
        redirect_to todos_path
    end

    def complete
        if @todo.completed == false
        @todo.completed = true
        elsif @todo.completed == true
        @todo.completed = false
        end
        @todo.save
        redirect_to todos_path
    end

    def list
        @todos = Todo.all
    end

    private

    def todo_params    
        params.require(:todo).permit(:description, :completed)
    end

    def find_todo
        @todo = Todo.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name = "viewport" content = "width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="https://stackpath.bootstrapcdn.com/bootswatch/4.3.1/minty/bootstrap.min.css" rel="stylesheet" integrity="sha384-9NlqO4dP5KfioUGS568UFwM3lbWf3Uj3Qb7FBHuIuhLoDp3ZgAqPE1/MYLEBPZYM" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
          <a class="navbar-brand" href="#">To Dos</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item active">
                <%= link_to "Index", todos_path, class: 'nav-link' %>
              </li>
              <li class="nav-item">
                <%= link_to  'List', todos_list_path, class: 'nav-link' %>
              </li>
              <li class="nav-item">
                <%= link_to  'New To Do', todos_new_path, class: 'nav-link' %>
              </li>
            </ul>
          </div>
        </nav>
    <div class = container>
    <%= yield %>
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/todos/_form.html.erb
<div class= 'col-mx-auto my-5'>
    <h2 class = "text-center font-weight-bold">Task</h2>
    <%= form_with(model: @todo, local: true) do|f|%>

    <div class="form-group font-weight-bold">
        <%= f.label 'Description:' %>
        <%= f.text_field :description, class: 'form-control'%>
    </div>

    <div class="form-group text-center font-weight-bold">
        <%= f.check_box :completed %> 
        <%= f.label 'Completed' %> 
    </div>

    <div class= "text-center my-5">
        <%= f.submit 'Save' %>
        <% end %>
    </div>
    <div class= "text-center font-weight-bold">
        <%= link_to "<< Back", todos_path %>
    </div>
</div>

app/views/todos/edit.html.erb
<div class= 'col-mx-auto my-5'>
<h1 class= text-center>EDIT YOUR TASK</h1>
<%= render 'form' %>
</div>

app/views/todos/index.html.erb
<div class= 'col-mx-auto my-5'>
<h1 class= 'text-center font-weight-bold'>TO DO LIST</h1>
<% @todos.each do|todo| %>
<br>
    <div class= 'text-center card card-body bg-light'>
        <p class = 'font-weight-bold'><%=todo.description%><p>
        <% if todo.completed == true%>
            <p class="card-text"><%= link_to "Mark as NOT Completed", complete_todo_path(todo), method: 'POST', class: "btn btn-danger" %></p>
        <% elsif todo.completed == false%>
            <p class="card-text"><%= link_to "Mark as Completed", complete_todo_path(todo), method: 'POST', class: "btn btn-success" %></p>
        <%end%>
        
        <div class = 'font-weight-bold'>
        <%= link_to 'Show', todo %> |
        <%= link_to 'Edit', edit_todo_path(todo) %> |
        <%= link_to "Delete", todo, method: :delete, data: {confirm: 'Are you sure?'} %>
        </div>
    </div>
<%end%>

<p class='text-center font-weight-bold py-5'><%= link_to 'Create new To Do', todos_new_path%></p>
</div>

app/views/todos/list.html.erb
<div class= 'col-mx-auto my-5'>
<h2 class = "text-center font-weight-bold">To Dos</h2>
<div class= 'row'>
    
    <div class = 'container col-md-6 my-5'>
        <h2 class = "text-center font-weight-bold">Not Completed To Dos</h2>
        <% @todos.each do|todo| %>
        <% if todo.completed == false %>
        <div class= ' text-center col-mx-auto my-3'>
            <div class= 'card card-body bg-danger text-light'>
                <%=todo.description%>
            </div>
        </div>
        <%end%>
        <%end%>
    </div>
    <div class = 'container col-md-6 my-5'>
        <h2 class = "text-center font-weight-bold">Completed To Dos</h2>
        <% @todos.each do|todo| %>
            <% if todo.completed == true %>
                <div class= ' text-center col-mx-auto my-3'>
                    <div class= 'card card-body bg-success text-light'>
                        <%=todo.description%>
                    </div>
                </div>
            <%end%>
        <%end%>
    </div>
</div>

app/views/todos/new.html.erb
<%= render 'form' %>

app/views/todos/show.html.erb
<div class= 'col-mx-auto my-5 text-center'>
<h1 class= text-center>YOUR TASK</h1>
<div class= 'jumbotron'>
<h4><%= @todo.description %></h4>
    <div class= 'font-weight-bold'>
    <% if @todo.completed == true %>
        <p class= 'text-success'>Completed!</p>
    <% else %>
        <p class= 'text-danger'>Task NOT completed yet</p>
    <% end %>
</div>
</div>
<div class = 'font-weight-bold text-center my-5'>
    <%= link_to 'Edit |', edit_todo_path(@todo) %>
    <%= link_to "Delete", @todo, method: :delete, data: {confirm: 'Are you sure?'} %>
</div>
<div class = 'font-weight-bold'>
    <%= link_to "<< Back", todos_path %>
</div>
</div>